# 'numpy

- one of the core packages for numerical computing in Python
- many packages are built on topy numpy
- numpy has been optimized for processing: faster due to memory access

In [3]:
# import Numpy with standard abbreviation
import numpy as np

#Variables

We can think about variables as a name we assign to a particular object in Python. For example:

In [9]:
# assign a small array to a variable a
a = np.array( [ [1,1,2], [3,5,8] ] )

In [ ]:
When we run a cell, we store the variable and its value

In [10]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [13]:
array([[1,1,2],
      [3,5,8]])

NameError: name 'array' is not defined

##naming variables

in the class we are going to use 'snake case

#Variables and objects

**object**: often encountered in Python documentation and tutorials. 

object is a bundle of properties and actions about something specific 

Example:
- object: dataframe
- properties: numbers of rows, names of columns, data created
- actions: selecting a row, adding a column

A variable is a name we give a specific object, and the same object can be referenced by different variables.

Examples:

- The Sun (actual star at the center of solar system) = object
- sol = Spanish word for Sun = variable
- soleil = Fren for Sun = another variable

In practice: we will use object and variable interchangeably 

# Types

Each object in Python has a type. 

type = what kind of object it is

We can also call the type of the object, the **class** of the object.

We can see the type/class of an object by using the type function:

In [14]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The numpy.ndarray is the core object/data type in the NumPy package. We can check the type of an entry in the array by indexing:

In [15]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

In [ ]:
# how would access the value 5 in the array a?

In [16]:
print(a)
a[1,1]

[[1 1 2]
 [3 5 8]]


5

In [17]:
a[1][1]

5

# Functions

'print' was our example of a Python function! :)

A function: 
- take in a set of **arguments**, separated by commas, and 
- use those arguments to produce some **output**

argument = parameter : you might argue more often in the documentation

We can ask information about a function by executing ? followed by the function name:

In [18]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- first line: function showing all of its arugments in parenthesis
- then a short description of what the function does
- finally, a list of the arguments and a brief explanation of each of them.

Different types of arguments inside the parenthesis. Roughly speaking, there are two types of arguments:

- **non-arguments**:arguments you need to specify for the function to do something
- **optional arguments**: arguments that are pre-filled with a dfault alue by the function, but we can override them. Optional arguments appear inside the parenthesis () in the form

'optional argument = default_value'

In [19]:
print('changing the default end argument of the print function', end=':)')

changing the default end argument of the print function:)

# Atttributes and Methods

An object in Python has attributes and methods.

- **attribute**: a property of an object, a piece of information about it.
- **method**: a procedure associated with an object, an action where the main ingredient is the object itself.

Access a variable's attributes ad methods by adding a period '.' at the end of the variable's name

'variable.variable_method()' or
'variable.variable_attribute'

Examples:

Methods and attributes of NumPy arrays"

In [1]:
import numpy as np

In [3]:
# define a 3x3 array 
var = np.array([[1,2,3] , [4,5,6], [7,8,9]])
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#shape : attribute telling us
#the number of elements in 


In [4]:
type(var.shape)

tuple

In [5]:
# ndim is an attribute holding the number of array dimensions
var.ndim

2

In [6]:
type(var.ndim)

int

Notice attribute can have many different adta types

Examples of methods:

In [7]:
# min method for array
# return the minumum value in the array
var.min()

1

In [8]:
type(var.min)

builtin_function_or_method

#R & Python

R: 
- doesn't use methods within an object
- functions in R are extrinsic to (outside) the objects they are acting on

Example: recreate getting teh min value in an array

In R there would be two separate items: the variable 'var' and a *separate* function 'min' that gets 'var' as a parameter:

```
# this is R code
var <- array(c(1,4,7,2,5,8,3,6,9), dim=c(3,3)
min(var)
```

Using the pipe operator >%> in R's tidyverse is closer to the '.' in Python:

```
var <- array(c(1,4,7,2,5,8,3,6,9), dim=c(3,3)
var >%> min()
```

What is happening?
The pipe `>%> is passing `var` to the `min()` as it first argument. This is essentially what teh '.' in Python is

```
var.min()
```